### ISSUE TITLE
Updated .catch() in interactionCreate from an interaction.reply to a console.log(error)

### ISSUE THREAD

**Issue by DBAggie** [DBAggie/discordBot#2]
Here is the result:

```
DiscordAPIError: Interaction has already been acknowledged.
    at RequestHandler.execute (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.reply (C:\Users\justi\Documents\bot\discordBot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:103:5)
    at async Object.execute (C:\Users\justi\Documents\bot\discordBot\commands\information\ping.js:9:3)
    at async Client.<anonymous> (C:\Users\justi\Documents\bot\discordBot\events\interactionCreate.js:14:5) {
  method: 'post',
  path: '/interactions/996231030321192980/aW50ZXJhY3Rpb246OTk2MjMxMDMwMzIxMTkyOTgwOlBpeXRpZW1VanJFSkduOXNqb053MnN0N1Z4RThscEx5ZEFSUDhRUENGdEpUZ3lWOUN5eU9teVRQaUg1Tm00VHdPanBGeE1ZRjNnd3hsNnhCdnlwM2o0NUNyS1g0TDhValFOWWpqS3lLRXh0U0NQZFJ3TWF2cmFzeWZ5N09hcVFh/callback',
  code: 40060,
  httpStatus: 400,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}
```

**Comment by tangjin0418** [comment]
Ok after a few tests, I find where's the problem.
You just listen to the event again for every `interactionCreate` fired.

So first it won't respond. And listen for a new `interactionCreate` event.
# Before

    module.exports = {
    	name: 'interactionCreate',
    	execute(interaction, client) {
    		client.on('interactionCreate', async interaction => {
    			console.log(`hit the interaction create script`)
    			if (!interaction.isCommand()) return console.log('Not a valid command');
    
    			const command = client.commands.get(interaction.commandName);
    
    			if (!command) return;
    
    			try {
    				console.log('Trying to execute')
    				await command.execute(interaction);
    			} catch (error) {
    				await interaction.reply({
    					content: 'There was an error while executing this command!',
    					ephemeral: true
    				});
    			}
    			console.log('Below the catch');
    		});
    		//console.log('Below the below catch message');
    	}
    };

# After

    module.exports = {
        name: "interactionCreate",
        async execute(interaction, client) {
            console.log(`hit the interaction create script`);
            if (!interaction.isCommand()) return console.log("Not a valid command");
    
            const command = client.commands.get(interaction.commandName);
    
            if (!command) return;
    
            try {
                console.log("Trying to execute");
                await command.execute(interaction);
            } catch (error) {
                await interaction.reply({
                    content: "There was an error while executing this command!",
                    ephemeral: true,
                });
            }
            console.log("Below the catch");
            //console.log('Below the below catch message');
        },
    };

See here? You listen for a new event when every interaction.

    execute(interaction, client) {
    	client.on('interactionCreate', async interaction => {

**Comment by tangjin0418** [comment]
And client id in config is unnecessary.
You can use `client.user.id` instead.
